services:
  - type: web
    name: splitmate-frontend
    env: static
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /landing_page
        destination: /index.html
      - type: rewrite
        source: /landing_page/
        destination: /index.html
      - type: rewrite
        source: "/*"
        destination: /index.html
