services:
  - type: web
    name: splitmate-frontend
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /landing_page
        destination: /index.html
      - type: rewrite
        source: "/*"
        destination: /index.html
